name: Deploy Streamlit app

on:
  push:
    branches:
      - main  # Trigger action only for the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # You can choose the Python version you prefer

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r task2/requirements.txt  # Reference requirements.txt inside the task2 folder

    - name: Deploy to Streamlit Cloud
      run: |
        curl -sSL https://streamlit.io/deploy-button-embed.js | python  # Deploy the app using Streamlit CLI
